export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Username': 'Username',
  'Password': 'Password',
  'Login': 'Login',
  'Signin': 'Log in',
  'Required': 'Field is required',
  'Unknown': 'Data not available',
  'Authenticate': 'Incorrect username or password',
  'BadRequest': 'Request error: the request has invalid syntax',
  'Unauthorized': 'Authorization error: no access rights to content',
  'Forbidden': 'Access error: no access rights to content',
  'Author': 'Levshevich I.M.',
  'Copyrights': 'All rights reserved',
  'Description': 'Description',
  'Performance': 'Performance',
  'Queue': 'Queue',
  'Type': 'Type',
  'State': 'State',
  'Running': 'Dispatcher running',
  'Aborted': 'Dispatcher suspended',
  'Stopped': 'Dispatcher stopped',
  'Run': 'Start',
  'Abort': 'Suspend',
  'Reset': 'Reset',
  'Stop': 'Stop',
  'Remove': 'Remove',
  'Refresh': 'Refresh',
  'Create': 'Create',
  'Operations': 'Operations',
  'Unavailable': 'Operations are not available',
  'LastRequestSpeed': 'Speed ​​of processing the last request in seconds',
  'QueueLength': 'Queue length',
  'Confirm': 'Confirm',
  'Cancel': 'Cancel',
  'RemoveDialogTitleQuestion': 'Are you sure?',
  'RemoveDialogTitleConfirm': 'Please confirm that you wish to delete dispatcher.',
  'Next': 'Next',
  'Back': 'Back',
  'Close': 'Close',
  'AddDialogTitle': 'Add dispatcher.',
  'AddDialogTitleType': 'Enter dispatchers type.',
  'AddDialogTitleDescription': 'Enter dispatchers description.',
  'AddDialogTitleInput': 'Enter dispatchers input parameters.',
  'InputHost': 'Server host (IPv4)',
  'InputPort': 'Server port',
  'InputUser': 'User name',
  'InputPassword': 'Password',
  'InputVhost': 'Virtual host',
  'InputExchange': 'Exchange',
  'InputQueue': 'Queue',
  'InputRoutingKey': 'Routing key',
  'AddDialogTitleOutput': 'Enter dispatchers output parameters.',
  'OutputHost': 'Client host (IPv4)',
  'OutputPort': 'Client port',
  'OutputUser': 'User name',
  'OutputPassword': 'Password',
  'OutputVhost': 'Virtual host',
  'OutputExchange': 'Exchange',
  'OutputQueue': 'Queue',
  'OutputRoutingKey': 'Routing key',
  'AddDialogTitleConfirm': 'Please confirm that you wish to add dispatcher.',
  'AddDialogTitleConfirmation': 'Confirmation.',
  'DetailsDialogTitle': 'View dispatcher.',
  'DetailsView': 'View dispatcher',
  'Shutdown': 'Shutdown CobaltUI',
  'ShutdownDialogTitleQuestion': 'Are you sure?',
  'ShutdownDialogTitleConfirm': 'Please confirm that you wish to shutdown CobaltUI.',
  'Messages': {
    'read': {
      'error': 'An error occurred while retrieving data: Code: {0}, decryption: {1}',
      'empty': 'Data not available',
      'status_error': 'An error occurred on the server side when receiving data'
    },
    'create': {
      'error': 'An error occurred while adding data: Code: {0}, decryption: {1}',
      'empty': 'Data not available',
      'status_error': 'An error occurred on the server side when adding data'
    },
    'update': {
      'error': 'An error occurred while changing the data: Code: {0}, decryption: {1}',
      'empty': 'Data not available',
      'status_error': 'An error occurred on the server side when changing data'
    },
    'remove': {
      'error': 'An error occurred while deleting data: Code: {0}, decryption: {1}',
      'empty': 'Data not available',
      'status_error': 'An error occurred on the server side when deleting data'
    }
  }
};
