export const LANG_RU_NAME = 'ru';

export const LANG_RU_TRANS = {
  'Username': 'Имя пользователя',
  'Password': 'Пароль',
  'Login': 'Вход',
  'Signin': 'Войти',
  'Required': 'Поле обязательно для заполнения',
  'Unknown': 'Данные не доступны',
  'Authenticate': 'Неверное имя пользователя или пароль',
  'BadRequest': 'Ошибка запроса: запрос имеет недопустимый синтаксис',
  'Unauthorized': 'Ошибка авторизации: нет прав доступа к контенту',
  'Forbidden': 'Ошибка доступа: нет прав доступа к контенту',
  'Author': 'Левшевич И.М.',
  'Copyrights': 'Все права защищены',
  'Description': 'Описание',
  'Performance': 'Производительность',
  'Queue': 'Очередь',
  'Type': 'Тип',
  'State': 'Состояние',
  'Running': 'Диспетчер запущен',
  'Aborted': 'Диспетчер приостановлен',
  'Stopped': 'Диспетчер остановлен',
  'Run': 'Запустить',
  'Abort': 'Приостановить',
  'Reset': 'Перезапустить',
  'Stop': 'Остановить',
  'Remove': 'Удалить',
  'Refresh': 'Обновить',
  'Create': 'Добавить',
  'Operations': 'Операции',
  'LastRequestSpeed': 'Скорость обработки последнего запроса в секундах',
  'QueueLength': 'Длина очереди',
  'Confirm': 'Подтвердить',
  'Cancel': 'Отменить',
  'Unavailable': 'Операции недоступны',
  'RemoveDialogTitleQuestion': 'Вы уверены?',
  'RemoveDialogTitleConfirm': 'Пожалуйста, подтвердите удаление диспетчера.',
  'Next': 'Далее',
  'Back': 'Назад',
  'Close': 'Закрыть',
  'AddDialogTitle': 'Добавить диспетчер.',
  'AddDialogTitleType': 'Введите тип диспетчера.',
  'AddDialogTitleDescription': 'Введите описание диспетчера.',
  'AddDialogTitleInput': 'Введите входные параметры диспетчера.',
  'InputHost': 'Серверный хост (IPv4)',
  'InputPort': 'Серверный порт',
  'InputUser': 'Пользователь',
  'InputPassword': 'Пароль',
  'InputVhost': 'Виртуальный хост',
  'InputExchange': 'Коммутатор',
  'InputQueue': 'Очередь',
  'InputRoutingKey': 'Ключ маршрутизации',
  'AddDialogTitleOutput': 'Введите выходные параметры диспетчера.',
  'OutputHost': 'Клиентский хост (IPv4)',
  'OutputPort': 'Клиентский порт',
  'OutputUser': 'Пользователь',
  'OutputPassword': 'Пароль',
  'OutputVhost': 'Виртуальный хост',
  'OutputExchange': 'Коммутатор',
  'OutputQueue': 'Очередь',
  'OutputRoutingKey': 'Ключ маршрутизации',
  'AddDialogTitleConfirm': 'Пожалуйста, подтвердите добавление диспетчера.',
  'AddDialogTitleConfirmation': 'Подтверждение.',
  'DetailsDialogTitle': 'Просмотр диспетчера.',
  'DetailsView': 'Просмотр диспетчера',
  'Shutdown': 'Выключить CobaltUI',
  'ShutdownDialogTitleQuestion': 'Вы уверены?',
  'ShutdownDialogTitleConfirm': 'Пожалуйста, подтвердите выключение CobaltUI.',
  'Messages': {
    'read': {
      'error': 'Произошла ошибка при получении данных: Код ошибки: {0}, расшифровка кода: {1}',
      'empty': 'Данные не доступны',
      'status_error': 'Произошла ошибка на стороне сервера при получении данных'
    },
    'create': {
      'error': 'Произошла ошибка при добавлении данных: Код ошибки: {0}, расшифровка кода: {1}',
      'empty': 'Данные не доступны',
      'status_error': 'Произошла ошибка на стороне сервера при добавлении данных'
    },
    'update': {
      'error': 'Произошла ошибка при изменении данных: Код ошибки: {0}, расшифровка кода: {1}',
      'empty': 'Данные не доступны',
      'status_error': 'Произошла ошибка на стороне сервера при изменении данных'
    },
    'remove': {
      'error': 'Произошла ошибка при удалении данных: Код ошибки: {0}, расшифровка кода: {1}',
      'empty': 'Данные не доступны',
      'status_error': 'Произошла ошибка на стороне сервера при удалении данных'
    }
  }
};
